services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run --token ${CF_TUNNEL_TOKEN}
    env_file:
      - .env
    networks:
      - core_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"  # falls du Watchtower nutzt

networks:
  core_net:
    external: true