services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data/vaultwarden:/data
    networks:
      - nginx_net
    secrets:
      - vaultwarden_admin_token
    environment:
      - WEBSOCKET_ENABLED=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"     # WebUI
      - "443:443"
    volumes:
      - ./data/npm/data:/data
      - ./data/npm/letsencrypt:/etc/letsencrypt
    networks:
      - nginx_net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - nginx_net
    secrets:
      - cloudflare_token
    command: >
      sh -c "cloudflared tunnel --no-autoupdate run --token $(cat /run/secrets/cloudflare_token)"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable
    networks:
      - nginx_net

secrets:
  vaultwarden_admin_token:
    file: ./secrets/vaultwarden_admin_token.txt
  cloudflare_token:
    file: ./secrets/cloudflare_token.txt

networks:
  nginx_net:
    external: true
