filenames:
 - /var/log/fail2ban.log*
 - /var/log/alternatives.log*
 - /var/log/dpkg.log*
labels:
 type: syslog

---
filenames:
 - /var/log/journal/*/system.journal
labels:
 type: journald

---
filenames:
 - /var/log/nginx/access.log
labels:
 type: nginx

---
filenames:
 - /var/lib/docker/containers/*/*.log
labels:
 type: docker
