filenames:
 - /var/log/auth.log
 - /var/log/fail2ban.log*
 - /var/log/journal/*
 - /var/log/syslog*
labels:
 type: syslog

---
filenames:
 - /var/log/nginx/access.log
labels:
 type: nginx

---
filenames:
 - /var/lib/docker/containers/*/*.log
labels:
 type: docker
