# CrowdSec main configuration (Git-managed)
# AppSec listener runs in separate container using appsec/appsec.yaml

common:
  daemonize: false
  pid_dir: /var/run/ # keep default
  log_media: stdout
  log_level: info

cscli:
  output: human
  color: auto

# Acquisition file listing log sources
crowdsec_service:
  acquisition_path: /etc/crowdsec/acquis.yaml

db_config:
  type: sqlite
  db_path: /var/lib/crowdsec/data/crowdsec.db

api:
  server:
    listen_uri: 0.0.0.0:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    log_level: info
  client:
    insecure_skip_verify: true

prometheus:
  enabled: true
  level: basic
  listen_addr: 0.0.0.0
  listen_port: 6060
