source_type: file
filenames:
  - /var/log/auth.log
labels:
  type: syslog

---
source_type: file
filenames:
  - /var/log/nginx/access.log
labels:
  type: nginx

---
source_type: file
filenames:
  - /var/lib/docker/containers/
labels:
  type: docker
