---
- Feuerwehr:
    - Feuerwehr Homepage:
        - abbr: FF
          href: https://www.ffw-windischletten.de/

    - KFV Bamberg:
      - abbr: KV
        href: https://www.kfv-ba.de/

    - LFV Bayern:
        - abbr: LV
          href: https://www.lfv-bayern.de/

    - Feuerwehr Lernbar:
        - abbr: FL
          href: https://www.feuerwehr-lernbar.bayern/home

    - Kreisjugendring Bamberg:
        - abbr: KB
          href: https://www.kjr-bamberg-land.de/

- Social:
    - Reddit:
        - icon: reddit.png
          href: https://reddit.com/
          description: The front page of the internet

    - Instagram:
        - icon: instagram.png
          href: https://instagram.com/
          description: Instagram

- Nützliches:
    - Selfhostec Icons:
        - abbr: SI
          href: https://selfh.st/icons/
