---
- Nützliches:
    - Feuerwehr Homepage:
        - abbr: FFW
          href: https://www.ffw-windischletten.de/

    - Selfhostec Icons:
        - abbr: SI
          href: https://selfh.st/icons/

    - KFV Bamberg:
      - abbr: KFV
        href: https://www.kfv-ba.de/

    - LFV Bayern:
        - abbr: LFV
          href: https://www.lfv-bayern.de/

    - Feuerwehr Lernbar:
        - abbr: FL
          href: https://www.feuerwehr-lernbar.bayern/home

    - Kreisjugendring Bamberg:
        - abbr: KB
          href: https://www.kjr-bamberg-land.de/
