- Infrastruktur:
    - Vaultwarden:
        icon: vaultwarden
        href: https://pw.ffw-windischletten.de
        description: Passwortmanager für die Feuerwehr
        siteMonitor: https://pw.ffw-windischletten.de
        showStats: true

    - Dashboard:
        icon: mdi-view-dashboard
        href: https://home.ffw-windischletten.de
        description: Übersicht und Schnellzugriff
        container: vaultwarden
        showStats: true

- Helferverwaltung:
    - Engelsystem:
        icon: mdi-fire-truck
        href: https://engelsystem.ffw-windischletten.de
        siteMonitor: https://engelsystem.ffw-windischletten.de
        description: Dienstplan und Helferkoordination
        showStats: true

- Weitere Dienste:
    - Placeholder App:
        icon: mdi-application
        href: https://demo.example.com
        siteMonitor: https://demo.example.com
        description: Hier könnte dein Service stehen
