- Tools:
    - Engelsystem:
        icon: mdi-fire-truck
        href: https://helfer.ffw-windischletten.de
        siteMonitor: https://helfer.ffw-windischletten.de
        container: engelsystem
        description: Dienstplan und Helferkoordination
        showStats: true

    - Einladungen:
        icon: mdi-application
        href: https://invites.ffw-windischletten.de/admin/
        siteMonitor: https://invites.ffw-windischletten.de
        container: simple_invites
        description: Einladungsverwaltung
        showStats: true

    - Vaultwarden:
        icon: vaultwarden
        href: https://pw.ffw-windischletten.de
        description: Passwortmanager für die Feuerwehr
        siteMonitor: https://pw.ffw-windischletten.de
        container: vaultwarden
        showStats: true

    - immich:
        icon: immich
        href: https://pics.ffw-windischletten.de
        description: Bilderverwaltung
        siteMonitor: https://pics.ffw-windischletten.de/photos
        container: immich_server
        showStats: true

- Cloud-Infrastruktur:
    - Dashboard:
        icon: mdi-view-dashboard
        href: https://home.ffw-windischletten.de
        description: Diese Seite
        siteMonitor: https://home.ffw-windischletten.de
        container: homepage
        showStats: true

    - Cloudflare Tunnel:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/cloudflare.svg
        description: Tunnelconnect für die Dienste
        container: cloudflared
        showStats: true

    - Watchtower:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/watchtower.svg
        description: Aktualisiert automatisch die Container
        container: watchtower
        showStats: true

    - Crowdsec:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/crowdsec.svg
        description: Crowdsourced IPS
        container: crowdsec
        showStats: true

    - Authentik:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/authentik.svg
        href: https://auth.ffw-windischletten.de
        description: Authentifizierungslösung
        container: authentik_server
        siteMonitor: https://auth.ffw-windischletten.de/if/flow/default-authentication-flow/?next=%2F
        showStats: true