- Cloud-Infrastruktur:
    - Dashboard:
        icon: mdi-view-dashboard
        href: https://home.ffw-windischletten.de
        description: Diese Seite
        siteMonitor: https://home.ffw-windischletten.de
        container: homepage
        showStats: true

    - Cloudflare Tunnel:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/cloudflare.svg
        description: Tunnelconnect für die Dienste
        container: cloudflared
        showStats: true

    - Watchtower:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/cloudflare.svg
        description: Aktualisiert automatisch die Container
        container: watchtower
        showStats: true

- Tools:
    - Engelsystem:
        icon: mdi-fire-truck
        href: https://engelsystem.ffw-windischletten.de
        siteMonitor: https://engelsystem.ffw-windischletten.de
        description: Dienstplan und Helferkoordination
        showStats: true

    - Einladungen:
        icon: mdi-application
        href: https://invites.ffw-windischletten.de/admin/
        siteMonitor: https://invites.ffw-windischletten.de
        container: simple_invites
        description: Einladungsverwaltung
        showStats: true

    - Vaultwarden:
        icon: vaultwarden
        href: https://pw.ffw-windischletten.de
        description: Passwortmanager für die Feuerwehr
        siteMonitor: https://pw.ffw-windischletten.de
        container: vaultwarden
        showStats: true
