title: FFW Windischletten Dashboard
description: Übersicht über alle Dienste auf dem VPS
theme: dark
color: slate
language: de
target: _blank
showStats: true
statusStyle: dot
useEqualHeights: true
headerStyle: boxed
fullWidth: true

layout:
  Tools:
    style: row
    columns: 3
  Cloud-Infrastruktur:
    style: row
    columns: 3
  Verwaltung:
    style: row
    columns: 3

