title: FFW Windischletten Dashboard
description: Übersicht über alle Dienste auf dem VPS
theme: dark
color: slate
language: de
target: _blank
showStats: true
statusStyle: dot
useEqualHeights: true
headerStyle: boxed
fullWidth: true
base: https://home.ffw-windischletten.de

layout:
  Infrastruktur:
    style: row
    columns: 3
  Verwaltung:
    style: row
    columns: 3
  Weitere Dienste:
    initiallyCollapsed: true
    style: row
    columns: 4
