- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
    unit: metric

- datetime:
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
    locale: de-DE

- search:
    provider: duckduckgo

- greeting:
    text_size: xl
    text: Herzlich Willkommen auf dem Dashboard der Feuerwehr Windischletten!
